#pragma once

#include "can_driver.h"
#define MAX_CAN_PAYLOAD_BTYES    8
#define BUFF_SIZE 32

#define WARN_OFFSET 0

//MOTOR CONTROLLER
#define MOTOR_CONTROLLER_1     0x10F8109A
#define MOTOR_CONTROLLER_2     0x10F8108D
//BMS
#define BMS_TEMP             0x10
#define BMS_WARN_OVERTEMP    0x06
//SENSORS
#define SENSOR_BOARD         0x10 // temp
#define SENSOR_BOARD_WARN     SENSOR_BOARD - WARN_OFFSET


// BEGIN MOTOR CONTROLLER BOARD DEFS
// FRAME 1
const DataSegment DRIVING_DIRECTION = {MOTOR_CONTROLLER_1, 1, 1};
const DataSegment MOTOR_SPEED = {MOTOR_CONTROLLER_1, 2, 3};
const DataSegment MOTOR_ERROR_CODE = {MOTOR_CONTROLLER_1, 4, 4}; 
//FRAME 2
const DataSegment BATTERY_VOLTAGE = {MOTOR_CONTROLLER_2, 1, 2};
const DataSegment BATTERY_CURRENT = {MOTOR_CONTROLLER_2, 3, 4};
const DataSegment MOTOR_TEMP = {MOTOR_CONTROLLER_2, 5, 6};
const DataSegment MOTOR_CONTROLLER_TEMP = {MOTOR_CONTROLLER_2, 7, 8};
//END MOTOR CONTROLLER BOARD DEFS

// BEGIN BMS DEFS

// END BMS DEFS

// BEGIN SENSORS BOARD DEFS
const DataSegment PRESSURE_SENSOR_DATA = {SENSOR_BOARD_PRIORITY, 1, 1}; 
const DataSegment IMU_DATA = {SENSOR_BOARD_PRIORITY, 2, 3};
const DataSegment LIM_ONE_TEMP = {SENSOR_BOARD_PRIORITY, 4, 5};
const DataSegment LIM_TWO_TEMP = {SENSOR_BOARD_PRIORITY, 6, 7};
const DataSegment ERROR_CODE = {SENSOR_BOARD_PRIORITY, 8, 8};
// END SENSORS BOARD DEFS
