#pragma once

#include "can_driver.h"
#define MAX_CAN_PAYLOAD_BTYES    8
#define BUFF_SIZE 32

// ID Defintions 
#define MC1     0x10F8109A
#define MC2     0x10F8108D
// CAN ARBITRATIONS FOR OTHER ENTITIES

#define BMS_TEMP 0x10
#define BMS_WARN_OVERTEMP 0x06
#define SENSOR_BOARD_PRIORITY 0x10 // temp
#define SENSOR_BOARD_PRIORITY_WARN 0x07



// MC1 DEFS 
const DataSegment DRIVING_DIRECTION = {MC1, 1, 1};
const DataSegment MOTOR_SPEED = {MC1, 2, 3};
const DataSegment MOTOR_ERROR_CODE = {MC1, 4, 4}; 


//END MC1 DEFS 

// MC2 DEFS 
const DataSegment BATTERY_VOLTAGE = {MC2, 1, 2};
const DataSegment BATTERY_CURRENT = {MC2, 3, 4};
const DataSegment MOTOR_TEMP = {MC2, 5, 6};
const DataSegment MOTOR_CONTROLLER_TEMP = {MC2, 7, 8};


//END MC2 DEFS 

// BMS BOARD DEFS
// BEGIN DEFS FOR THERMISTOR MESSAGE
const DataSegment MUX1_TEMP = {BMS_TEMP, 1, 1};
const DataSegment MUX2_TEMP = {BMS_TEMP, 2, 2};
const DataSegment MUX3_TEMP = {BMS_TEMP, 3, 3};
const DataSegment MUX4_TEMP = {BMS_TEMP, 4, 4};
const DataSegment MUX5_TEMP = {BMS_TEMP, 5, 5};
const DataSegment MUX6_TEMP = {BMS_TEMP, 6, 6};

// END DEFS FOR THERMISTOR MESSAGE

// BEGIN DEFS FOR ERROR STATES
const DataSegment MUX1_TEMP_WARN = {BMS_WARN_OVERTEMP, 1, 1};
const DataSegment MUX2_TEMP_WARN = {BMS_WARN_OVERTEMP, 2, 2};
const DataSegment MUX3_TEMP_WARN = {BMS_WARN_OVERTEMP, 3, 3};
const DataSegment MUX4_TEMP_WARN = {BMS_WARN_OVERTEMP, 4, 4};
const DataSegment MUX5_TEMP_WARN = {BMS_WARN_OVERTEMP, 5, 5};
const DataSegment MUX6_TEMP_WARN = {BMS_WARN_OVERTEMP, 6, 6};
// END DEFS FOR ERROR STATES


// 

// BEGIN SENSORS BOARD DEFN 
// STANDARD IDS 
const DataSegment PRESSURE_SENSOR_DATA = {SENSOR_BOARD_PRIORITY, 1, 1};
const DataSegment IMU_DATA = {SENSOR_BOARD_PRIORITY, 2, 3};
const DataSegment LIM_ONE_TEMP = {SENSOR_BOARD_PRIORITY, 4, 5};
const DataSegment LIM_TWO_TEMP = {SENSOR_BOARD_PRIORITY, 6, 7};
const DataSegment ERROR_CODE = {SENSOR_BOARD_PRIORITY, 8, 8};
// WARN IDS 
const DataSegment PRESSURE_SENSOR_DATA_WARN = {SENSOR_BOARD_PRIORITY_WARN, 1, 1};
const DataSegment IMU_DATA_WARN = {SENSOR_BOARD_PRIORITY_WARN, 2, 3}; 
const DataSegment LIM_ONE_TEMP_WARN = {SENSOR_BOARD_PRIORITY_WARN, 4, 5};
const DataSegment LIM_TWO_TEMP_WARN = {SENSOR_BOARD_PRIORITY_WARN, 6, 7};
const DataSegment ERROR_CODE_WARN = {SENSOR_BOARD_PRIORITY_WARN, 8, 8};

// END SENSORS BOARD DEFN